CITY_AIRPORT_CODES = {
    "西安": "SIA",
    "北京": "PEK",
    "上海": "SHA",
    "杭州": "HGH",
    "南京": "NKG",
    "苏州": "SZV",
    "广州": "CAN",
    "深圳": "SZX",
    "成都": "CTU",
    "重庆": "CKG",
    "武汉": "WUH",
    "长沙": "CSX",
    "青岛": "TAO",
}
